services:
  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    container_name: taskflow-api
    restart: unless-stopped
    env_file:
      - .production.env
      - .production.local.env
    networks:
      - shared-network

  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL : https://api-taskflow.asik.work
    container_name: taskflow-web
    restart: unless-stopped
    env_file:
      - .production.env
      - .production.local.env
    networks:
      - shared-network

networks:
  shared-network:
    external: true